kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: new-joiner
rules:
  - apiGroups: ["", "apps", "autoscaling", "extensions"] #core api and apps
    resources: ["*"] #pods, services, deployments...
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: add-user-to-new-joiner-role
subjects:
  # List users that are going to have this role
  - kind: User
    name: francis-linux-login-name
roleRef:
  kind: ClusterRole
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: playground-full-access
  namespace: playground
rules:
  - apiGroups: ["*"] #core api and apps
    resources: ["*"] #pods, services, deployments...
    verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: add-user-to-playground-full-access
  namespace: playground
subjects:
  # List users that are going to have this role
  - kind: User
    name: francis-linux-login-name
roleRef:
  kind: Role
  name: playground-full-access
  apiGroup: rbac.authorization.k8s.io