kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: new-joiner
  namespace: default
rules:
  - apiGroups: ["", "apps"] #core api and apps
    resources: ["*"] #pods, services, deployments...
    verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: add-user-to-new-joiner-role
  namespace: default
subjects:
  # List users that are going to have this role
  - kind: User
    name: francis
roleRef:
  kind: Role
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io